apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/[0-9a-zA-Z]+)$ $1/ redirect;
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - service.peijun.me
    - app.peijun.me
    secretName: default-tls-secret
  rules:
  - host: service.peijun.me
    http:
      paths:
        - path: /lightsoff(/|$)(.*)
          backend:
            serviceName: lightsoff
            servicePort: 5000
  - host: app.peijun.me
    http:
      paths:
        - path: /lightsoff(/|$)(.*)
          backend:
            serviceName: lightsoff-app
            servicePort: 5000
